version: '3.4'

services:
  library:
    image: ${DOCKER_REGISTRY-}library
    build:
      context: .
      dockerfile: Library/Dockerfile
    ports:
     - 5000:80
    depends_on:
     - db
  db:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
        ACCEPT_EULA: Y
        MSSQL_SA_PASSWORD: Mysqlpass1
